[build]
  command = "cd medo-main && npm run build"
  publish = "medo-main/one part/my-protofile-main/dist"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "medo-main/one part/my-protofile-main/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

